PRODUCT_CATALOG_FIELD_PRODUCT_ID = "id"
PRODUCT_CATALOG_FIELD_PRODUCT_IMAGE = "image_url"

FEATURES_CATALOG_FIELD_PRODUCT_ID = "product_id"
FEATURES_CATALOG_FIELD_PRODUCT_FEATURE = "product_feature"

PRODUCTS_INFO_CATALOG_FILE = "product_info.pkl"
PRODUCTS_FEATURES_CATALOG_FILE = "product_features.pkl"
